name: blocksettle 
version: 0.20.4
summary: Cross-Platform Bitcoin Wallet
description: |
     BlockSettle Terminal is BitCoin wallet that works with ArmoryDB 
     local and remote instances.

confinement: devmode
base: core18

parts:
  terminal:
    plugin: dump
    source: terminal_release.tar.bz2
#    after:
#      - desktop-qt5
    build-attributes: [keep-execstack]
    stage-packages:
      - libqt5core5a
      - libxml2-dev
      - libfontconfig
      - qt5-default
      - libx11-6
      - libxcb-xinerama0
      - libdb5.3
      - libpng16-16
      - libcups2
      - libxcb-shm0
      - libdbus-1-3
      #- libdouble-conversion1v5
      - libdouble-conversion1
      - libuuid1
      - libsystemd0 
        #      - libc6
apps:
  terminal:
    command: terminal

